# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
