# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20170609_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='logo',
        ),
    ]
