# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_movies_modifiedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movieid',
            field=models.IntegerField(default=0),
        ),
    ]
